package forge.card;

import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

import com.google.common.collect.Maps;

/**
 * Flavor text for card printings, which Forge otherwise doesn't carry at all.
 * <p>
 * Only a handful of Unhinged cards read it (Punctuate and Pygmy Giant count things in a text box,
 * which per the Unhinged FAQ includes flavor text; Meddling Kids and Tainted Monkey look for a word
 * in one), but any card in the pool can be their target, so the table has to cover everything. It is
 * therefore loaded lazily - a game that never plays one of those cards never pays for it.
 * <p>
 * Keyed by edition code and collector number because flavor text belongs to a printing rather than a
 * card: Pygmy Giant's "487" exists only on the Unhinged printing. Generated by
 * {@code _tools/flavor-text/extract.js} from Scryfall bulk data.
 */
public final class CardFlavorText {
    private CardFlavorText() { }

    private static Supplier<List<String>> source = null;
    private static Map<String, String> table = null;

    /** Set by the GUI layer at startup; the file isn't read until something actually asks for it. */
    public static synchronized void setSource(final Supplier<List<String>> lineSource) {
        source = lineSource;
        table = null;
    }

    private static synchronized Map<String, String> table() {
        if (table != null) {
            return table;
        }
        table = Maps.newHashMapWithExpectedSize(60000);
        if (source == null) {
            return table;
        }
        for (final String line : source.get()) {
            // SET|collector|flavor, with \n escapes - the flavor itself may contain | so split twice
            final int firstBar = line.indexOf('|');
            if (firstBar < 0) {
                continue;
            }
            final int secondBar = line.indexOf('|', firstBar + 1);
            if (secondBar < 0) {
                continue;
            }
            table.put(line.substring(0, secondBar),
                    line.substring(secondBar + 1).replace("\\n", "\n").replace("\\\\", "\\"));
        }
        return table;
    }

    /** Flavor text of this printing, or an empty string when it has none. */
    public static String get(final String edition, final String collectorNumber) {
        if (edition == null || collectorNumber == null) {
            return "";
        }
        return table().getOrDefault(edition.toUpperCase() + "|" + collectorNumber, "");
    }
}
