package forge.card;

import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

import com.google.common.collect.Maps;

/**
 * Facts about a physical printing that Forge's edition files don't carry: its watermark, whether its
 * artwork shows an open mouth, and its border where the edition data gets it wrong or can't say
 * (borderless printings have no edition-level equivalent). Knight of the Kitchen Sink is what reads
 * them, but any card in the pool can be on the other side of its protection, so the table covers
 * everything. Loaded lazily, like {@link CardFlavorText}.
 * <p>
 * Keyed by edition code and collector number; token printings are prefixed with "@" because they
 * share both with the set's cards (UST token 12 vs Knight of the Kitchen Sink 12a). Generated by
 * {@code _tools/printing-traits/generate.js} from Scryfall bulk data, with open mouths taken from
 * Scryfall Tagger's art tags - community-curated, so an untagged open mouth reads as closed. Lines of text
 * ("wordy", Lexivore's "most lines of text") are counted on each printing's card image by
 * {@code _tools/rules-lines}.
 */
public final class PrintingTraits {
    private PrintingTraits() { }

    private static Supplier<List<String>> source = null;
    private static Map<String, Traits> table = null;

    public static final class Traits {
        private CardEdition.BorderColor border = null;
        private String watermark = null;
        private String backWatermark = null;
        private boolean openMouth = false;
        private boolean backOpenMouth = false;
        private boolean facingLeft = false;
        private boolean facingRight = false;
        private boolean backFacingLeft = false;
        private boolean backFacingRight = false;
        private int figures = 0;
        private int backFigures = 0;
        private int rulesLines = -1;
        private int backRulesLines = -1;
        private int textLines = -1;
        private int backTextLines = -1;
        private boolean hat = false;
        private boolean backHat = false;
        private boolean tree = false;
        private boolean backTree = false;

        /** The border as printed, or null when the edition data already has it right. */
        public CardEdition.BorderColor getBorder() {
            return border;
        }

        public String getWatermark(final boolean backFace) {
            return backFace ? backWatermark : watermark;
        }

        public boolean hasOpenMouth(final boolean backFace) {
            return backFace ? backOpenMouth : openMouth;
        }

        /** Scryfall Tagger's left-facing tag on the artwork (as seen by the viewer). */
        public boolean isFacingLeft(final boolean backFace) {
            return backFace ? backFacingLeft : facingLeft;
        }

        /** Scryfall Tagger's right-facing tag on the artwork (as seen by the viewer). */
        public boolean isFacingRight(final boolean backFace) {
            return backFace ? backFacingRight : facingRight;
        }

        /** Figures in the artwork per Scryfall Tagger: 1 (solo), 2 (two or more), or 0 when untagged. */
        public int getArtFigures(final boolean backFace) {
            return backFace ? backFigures : figures;
        }

        /** Printed lines of rules text, counted on the card image; -1 when they couldn't be read. */
        public int getRulesLines(final boolean backFace) {
            return backFace ? backRulesLines : rulesLines;
        }

        /** A hat on single-figure art (Goblin Haberdasher), so on the creature itself; false can still mean untagged. */
        public boolean hasHat(final boolean backFace) {
            return backFace ? backHat : hat;
        }

        /** A tree in the artwork (Selfie Preservation), per Scryfall Tagger; false can still mean untagged. */
        public boolean hasTree(final boolean backFace) {
            return backFace ? backTree : tree;
        }

        /** Printed lines in the whole text box, flavor text included (Lexivore); -1 when they couldn't be read. */
        public int getTextLines(final boolean backFace) {
            return backFace ? backTextLines : textLines;
        }
    }

    /** Set by the GUI layer at startup; the file isn't read until something actually asks for it. */
    public static synchronized void setSource(final Supplier<List<String>> lineSource) {
        source = lineSource;
        table = null;
    }

    private static synchronized Map<String, Traits> table() {
        if (table != null) {
            return table;
        }
        table = Maps.newHashMapWithExpectedSize(30000);
        if (source == null) {
            return table;
        }
        for (final String line : source.get()) {
            // CODE|collector|trait|trait...
            final String[] parts = line.split("\\|");
            if (parts.length < 3) {
                continue;
            }
            final Traits t = new Traits();
            for (int i = 2; i < parts.length; i++) {
                final String trait = parts[i];
                if (trait.startsWith("border=")) {
                    try {
                        t.border = CardEdition.BorderColor.valueOf(trait.substring(7).toUpperCase());
                    } catch (IllegalArgumentException e) {
                        System.err.println("PrintingTraits: unknown border in " + line);
                    }
                } else if (trait.startsWith("watermark=")) {
                    t.watermark = trait.substring(10);
                } else if (trait.startsWith("backwatermark=")) {
                    t.backWatermark = trait.substring(14);
                } else if (trait.equals("openmouth")) {
                    t.openMouth = true;
                } else if (trait.equals("backopenmouth")) {
                    t.backOpenMouth = true;
                } else if (trait.equals("facingleft")) {
                    t.facingLeft = true;
                } else if (trait.equals("facingright")) {
                    t.facingRight = true;
                } else if (trait.equals("backfacingleft")) {
                    t.backFacingLeft = true;
                } else if (trait.equals("backfacingright")) {
                    t.backFacingRight = true;
                } else if (trait.startsWith("figures=")) {
                    t.figures = trait.endsWith("multi") ? 2 : 1;
                } else if (trait.startsWith("backfigures=")) {
                    t.backFigures = trait.endsWith("multi") ? 2 : 1;
                } else if (trait.startsWith("rulelines=")) {
                    t.rulesLines = Integer.parseInt(trait.substring(10));
                } else if (trait.startsWith("backrulelines=")) {
                    t.backRulesLines = Integer.parseInt(trait.substring(14));
                } else if (trait.equals("hat")) {
                    t.hat = true;
                } else if (trait.equals("backhat")) {
                    t.backHat = true;
                } else if (trait.equals("tree")) {
                    t.tree = true;
                } else if (trait.equals("backtree")) {
                    t.backTree = true;
                } else if (trait.startsWith("textlines=")) {
                    t.textLines = Integer.parseInt(trait.substring(10));
                } else if (trait.startsWith("backtextlines=")) {
                    t.backTextLines = Integer.parseInt(trait.substring(14));
                }
            }
            table.put(parts[0].toUpperCase() + "|" + parts[1], t);
        }
        return table;
    }

    /** Traits of this printing, or null when it has none worth recording. */
    public static Traits get(final String edition, final String collectorNumber, final boolean token) {
        if (edition == null || collectorNumber == null) {
            return null;
        }
        return table().get((token ? "@" : "") + edition.toUpperCase() + "|" + collectorNumber);
    }
}
