package forge.card;

import java.util.List;
import java.util.Map;
import java.util.function.Supplier;

import com.google.common.collect.Maps;

/**
 * Facts about a physical printing that Forge's edition files don't carry: its watermark, whether its
 * artwork shows an open mouth, and its border where the edition data gets it wrong or can't say
 * (borderless printings have no edition-level equivalent). Knight of the Kitchen Sink is what reads
 * them, but any card in the pool can be on the other side of its protection, so the table covers
 * everything. Loaded lazily, like {@link CardFlavorText}.
 * <p>
 * Keyed by edition code and collector number; token printings are prefixed with "@" because they
 * share both with the set's cards (UST token 12 vs Knight of the Kitchen Sink 12a). Generated by
 * {@code _tools/printing-traits/generate.js} from Scryfall bulk data, with open mouths taken from
 * Scryfall Tagger's art tags - community-curated, so an untagged open mouth reads as closed.
 */
public final class PrintingTraits {
    private PrintingTraits() { }

    private static Supplier<List<String>> source = null;
    private static Map<String, Traits> table = null;

    public static final class Traits {
        private CardEdition.BorderColor border = null;
        private String watermark = null;
        private String backWatermark = null;
        private boolean openMouth = false;
        private boolean backOpenMouth = false;

        /** The border as printed, or null when the edition data already has it right. */
        public CardEdition.BorderColor getBorder() {
            return border;
        }

        public String getWatermark(final boolean backFace) {
            return backFace ? backWatermark : watermark;
        }

        public boolean hasOpenMouth(final boolean backFace) {
            return backFace ? backOpenMouth : openMouth;
        }
    }

    /** Set by the GUI layer at startup; the file isn't read until something actually asks for it. */
    public static synchronized void setSource(final Supplier<List<String>> lineSource) {
        source = lineSource;
        table = null;
    }

    private static synchronized Map<String, Traits> table() {
        if (table != null) {
            return table;
        }
        table = Maps.newHashMapWithExpectedSize(30000);
        if (source == null) {
            return table;
        }
        for (final String line : source.get()) {
            // CODE|collector|trait|trait...
            final String[] parts = line.split("\\|");
            if (parts.length < 3) {
                continue;
            }
            final Traits t = new Traits();
            for (int i = 2; i < parts.length; i++) {
                final String trait = parts[i];
                if (trait.startsWith("border=")) {
                    try {
                        t.border = CardEdition.BorderColor.valueOf(trait.substring(7).toUpperCase());
                    } catch (IllegalArgumentException e) {
                        System.err.println("PrintingTraits: unknown border in " + line);
                    }
                } else if (trait.startsWith("watermark=")) {
                    t.watermark = trait.substring(10);
                } else if (trait.startsWith("backwatermark=")) {
                    t.backWatermark = trait.substring(14);
                } else if (trait.equals("openmouth")) {
                    t.openMouth = true;
                } else if (trait.equals("backopenmouth")) {
                    t.backOpenMouth = true;
                }
            }
            table.put(parts[0].toUpperCase() + "|" + parts[1], t);
        }
        return table;
    }

    /** Traits of this printing, or null when it has none worth recording. */
    public static Traits get(final String edition, final String collectorNumber, final boolean token) {
        if (edition == null || collectorNumber == null) {
            return null;
        }
        return table().get((token ? "@" : "") + edition.toUpperCase() + "|" + collectorNumber);
    }
}
